export default [
    {
        id:1,
        Image:"",
        Githublink:"",
        urlLink:"",
    },
    {
        id:2,
        Image:"",
        Githublink:"",
        urlLink:"",
    },
    {
        id:3,
        Image:"",
        Githublink:"",
        urlLink:"",
    },
    {
        id:4,
        Image:"",
        Githublink:"",
        urlLink:"",
    },
    {
        id:5,
        Image:"",
        Githublink:"",
        urlLink:"",
    },
    {
        id:6,
        Image:"",
        Githublink:"",
        urlLink:"",
    },
   
]